import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "./bottomNav";
import Navbar from "./navbar";
import User from "@components/User";

const inter = Roboto_Mono({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <User />
        <div className="card border-t-2 p-4 pb-16" id="border-card">
          {children}
        </div>
        <BottomNav />
      </body>
    </html>
  );
}
