import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Script from "next/script";
import AppProvider from "@components/layouts/AppProvider";
import LayoutHome from "@components/layouts";
import { isMobile } from "react-device-detect";

const inter = Roboto_Mono({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          strategy="beforeInteractive"
          src="https://telegram.org/js/telegram-web-app.js"
        />
      </head>
      <body className={inter.className}>
        <AppProvider>
          <LayoutHome>
            {children}
          </LayoutHome>
        </AppProvider>
      </body>
    </html>
  );
}
